### ISSUE TITLE
How do I update the self-host bot without harming the original file? (Because I have already translated the text part.)

### ISSUE THREAD

**Issue by Ray-Hsueh** [Ballsdex-Team/BallsDex-DiscordBot#276]
How do I update the self-host bot without harming the original file? (Because I have already translated the text part. I do not want to re-translate it because that would be a great effort.)

**Comment by laggron42** [comment]
You have to play with git to update and keep your changes.

The good news is, git handles conflicts very well, if you update you will get a list of places that conflict and be able to resolve them. If we haven't changed the text on our end, then git will cleverly merge your changes with ours and you'll keep your translations while getting the latest features.

The bad news, git is not easy to use. I can only point you to the right directions because this is out of scope of the bot. Make a stash with your branches (`git stash`), update the bot (`git pull`) and see what conflicts you end up with. If you have some, you can follow [git's tutorial](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts) to fix them, or really anything online, it's widely covered. (VScode comes with built-in features to handle conflicts btw)
