### ISSUE TITLE
It is saying no module name ballsdex

### ISSUE THREAD

**Issue by GamingLina0509** [Ballsdex-Team/BallsDex-DiscordBot#80]
how can i make it so it does not say it. I have little experience of coding
![Screenshot 2023-04-21 12 07 39 PM](https://user-images.githubusercontent.com/78812341/233683884-37f5ef8a-11c0-4cef-9135-005bdd409d94.png)

**Comment by ltzmax** [comment]
Please make sure you have actually [followed the wiki](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki) correctly.

**Comment by laggron42** [comment]
It looks like you're trying to run the bot in replit, you can forget that. Not only will it be considerably hard to get running and require a lot of changes in the code, you also need a running PostgreSQL instance, and Replit has no free tier for that, you need to pay money in any case (I assume you went for replit because it offers free tiers).

Cheapest option is to rent a VPS, but that requires knowledge on how to configure and use Linux, which is out of scope to the issues from this repo.
