### ISSUE TITLE
Balls completion not working

### ISSUE THREAD

**Issue by VendeBon** [Ballsdex-Team/BallsDex-DiscordBot#81]
![image](https://user-images.githubusercontent.com/131602039/233846341-97a43739-476d-49d6-8d45-b93da9e162f5.png)
How do i fix it?

**Comment by laggron42** [comment]
Can you check your docker logs and see what went wrong?

**Comment by VendeBon** [comment]
when i loaded the bot in the cmd i saw a text "intent is missing, commands may not work as intended"
![image](https://user-images.githubusercontent.com/131602039/235324277-574812eb-4a09-4d75-9ee4-d68397bde5f9.png)

**Comment by laggron42** [comment]
Uhh, you're running a seriously outdated version and we're not supporting that. You've probably hit a bug that was fixed a long time ago now.

Please take a look at the wiki for updating, more specifically [how to migrate to a git install](https://github.com/Ballsdex-Team/BallsDex-DiscordBot/wiki/Migrating-to-a-git-install) because I suppose that was installed in the wrong way, such that it cannot be updated.
